[workspace]
channels = ["conda-forge"]
name = "franka-foresight"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = "<3.11"
matplotlib = ">=3.10.8,<4"
cudatoolkit = ">=11.8.0,<12"
scikit-learn = ">=1.7.2,<2"
ipykernel = ">=7.1.0,<8"
tqdm = ">=4.67.1,<5"
gymnasium-robotics = ">=1.4.1,<2"

[pypi-options]
extra-index-urls = ["https://download.pytorch.org/whl/cu130"]

[pypi-dependencies]
torch = "==2.9.0"
torchvision = "==0.24.0"
torchaudio = "==2.9.0"
